// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBijdsmD7aSI6gOKkd-H_4pp7mA5y1iDqM',
    appId: '1:271581177340:web:11cc60dc52e40fa1b7fe79',
    messagingSenderId: '271581177340',
    projectId: 'messaging-app-d2ae6',
    authDomain: 'messaging-app-d2ae6.firebaseapp.com',
    storageBucket: 'messaging-app-d2ae6.firebasestorage.app',
    measurementId: 'G-5B2CYXTYN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTX4ng0FxqtiqZI0reomnTiwHR_lH5EY',
    appId: '1:271581177340:android:12a01c15be308ceab7fe79',
    messagingSenderId: '271581177340',
    projectId: 'messaging-app-d2ae6',
    storageBucket: 'messaging-app-d2ae6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMcOGnPoP02EtgU6sW_n4v5wjRLVUxIQU',
    appId: '1:271581177340:ios:a74dbdcf07428a24b7fe79',
    messagingSenderId: '271581177340',
    projectId: 'messaging-app-d2ae6',
    storageBucket: 'messaging-app-d2ae6.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMcOGnPoP02EtgU6sW_n4v5wjRLVUxIQU',
    appId: '1:271581177340:ios:a74dbdcf07428a24b7fe79',
    messagingSenderId: '271581177340',
    projectId: 'messaging-app-d2ae6',
    storageBucket: 'messaging-app-d2ae6.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBijdsmD7aSI6gOKkd-H_4pp7mA5y1iDqM',
    appId: '1:271581177340:web:e693c3795aa9c15db7fe79',
    messagingSenderId: '271581177340',
    projectId: 'messaging-app-d2ae6',
    authDomain: 'messaging-app-d2ae6.firebaseapp.com',
    storageBucket: 'messaging-app-d2ae6.firebasestorage.app',
    measurementId: 'G-BKH90RK0BK',
  );
}
